platform :ios, '13.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  # pod 'mokoMvvmFlowSwiftUI', :podspec => '../../mokoMvvmFlowSwiftUI.podspec'
end
